### ISSUE TITLE
Make StationaryRandomFields follow either the MeasureBase or Distributions interface

### ISSUE THREAD

**Issue by ptiede** [EHTJulia/StationaryRandomFields.jl#4]
These stationary random fields are Gaussian processes yet we do not treat them like that in this package.  We should probably define the Stationary random field as a `AbstractContinuousDistribution` and define methods based on that. The interface is defined here [https://juliastats.org/Distributions.jl/stable/extends/](). The only thing we would need to think about is the whitening or diagonalizing parameterization of the distribution we intrinsically use here. Namely, by generating random numbers like `x = FFT(PS .* z)` where `z` are Gaussian random numbers. With this parameterization are intrinsically using a matrix square root factorization of the covariance matrix. This means that the pdf of the distribution would just be the pdf of the `z` but if we are calculating the pdf of the generated image we would need to calculate `x inv(C) x` where `C` is the covariance matrix.  We could deal with this in a few ways the simplest would be to just enforce this parameterization from the beginning and say that `logpdf(d, x)` just by default uses an uncorrelated Normal distribution but `rand` generates the true correlated field. 

The other approach that eventually we probably want to adopt is to follow `MeasureBase.jl` and implement these as measures and use the `PushFwd` measure and the transport interface to automate this over the entire Julia ecosystem. I'm a little hesitant to use it right now since it is going under a pretty large refactor but once the API stabilizes we should probably adopt this.

**Comment by kazuakiyama** [comment]
I would close this issue as the design choice is being made and we follow Distributions.jl. See the issue (#5) to follow up on this task.
